<?php
/**
 * Created by PhpStorm.
 * User: oscar
 * Date: 31/01/18
 * Time: 09:54 PM
 */

class Tgec_admin{


    /**Page IDs generated by add_menu functions. Used internally for CSS purposes*/
    public $main_page_id;
    public $add_new_event_id;

    /**URLS of different admin pages */
    public $admin_url;
    public $admin_add_new_url;

    /**Constructor */
    public function __construct(){
        add_action( 'admin_menu', array( $this, 'tgec_admin_menus' ) );
    }

    /**Registers Menus */
    public function tgec_admin_menus(){

        $main_slug = 'wp-tgec';
        $add_new_slug = 'tgec-add-new';

        //Adds Main Menu to wp-admin
        $this->main_page_id =
            add_menu_page(
              'TGE Calendar',
              'TGE Calendar',
              'administrator',
              $main_slug, //menu-slug
              array( $this, 'tgec_admin_page_main' ) //callback function
            );

        //Adds sub-menu for Add-new event
        $this->add_new_event_id =
            add_submenu_page(
                'wp-tgec',
                'Add new',
                'Add new',
                'administrator',
                $add_new_slug,
                array($this, 'tgec_admin_page_add_new')
            );

        //URLS of different admin pages
        $this->admin_url = admin_url( 'admin.php?page=' . $main_slug );
        $this->admin_add_new_url = admin_url( 'admin.php?page=' . $add_new_slug );
    }

    /** Renders the whole admin page */
    public function tgec_admin_page_main(){
        $this->tgec_admin_page_header();
    }

    /** Renders the Admin page Header */
    private function tgec_admin_page_header( $active_page = 'event-list' ){
        ?>
        <div id="tge-admin-page" class="wrap">
            <header>
                <h1 id="tge-title">The great events Calendar</h1>
                <h2 class="nav-tab-wrapper">
                    <?php
                    if( current_user_can( 'administrator' ) || ( 'editor' ) ){
                        ?>
                        <a href="<?php echo $this->admin_url;?>" class="nav-tab<?php echo ( 'event-list' == $active_page )? ' nav-tab-active' : '';?>">
                            <?php echo _e('All events'); ?>
                        </a>
                        <a href="<?php echo $this->admin_add_new_url;?>" class="nav-tab<?php echo ( 'new-event' == $active_page )? ' nav-tab-active' : '';?>">
                            <?php _ex( 'Add New', 'submenu item text', 'wp-tgec' ); ?>
                        </a>
                        <?php
                    }
                    else{
                        echo 'Sorry, you do not have access';
                    }
                    ?>
                </h2>
            </header>
        </div>
        <?php
    }

    /** Renders Add New Event Admin Page */
    public function tgec_admin_page_add_new() {

        $this->tgec_admin_page_header( 'new-event' );
    }

}



